import { useState } from "react";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from 'recharts';
import rawData from '../other/IBM_stock_data.json';

interface TimeSeriesData {
    [date: string]: {
        "1. open": string;
        "2. high": string;
        "3. low": string;
        "4. close": string;
        "5. volume": string;
    };
}

interface StockData {
    "Meta Data": {
        "1. Information": string;
        "2. Symbol": string;
        "3. Last Refreshed": string;
        "4. Output Size": string;
        "5. Time Zone": string;
    };
    "Time Series (Daily)": TimeSeriesData;
}

interface ChartData {
    date: string;
    price: number;
}

const AmaricaStocks = () => {
    const [showMore, setShowMore] = useState(false);

    const toggleShowMore = () => {
        setShowMore(!showMore);
    };

    const processData = (data: StockData): ChartData[] => {
        const timeSeries = data["Time Series (Daily)"];
        return Object.keys(timeSeries).map((date) => ({
            date, 
            price: parseFloat(timeSeries[date]["4. close"]),
        })).reverse();
    };

    const chartData: ChartData[] = processData(rawData);

    return (
        <>
            <div className="flex items-center">
                <div className="bg-slate-950 ps-10 pe-10 pt-3 pb-3 rounded-md text-white me-3">
                    <p className="font-bold text-2xl">IBM</p>
                </div>

                <div className="company_detail text-brown-sugar">
                    <h1 className="font-semibold text-xl">International Business Machines</h1>
                    <div className="curreny_type flex items-center">
                        <img src="./usa-circle-flag.png" width={25} className="pe-2" alt="usa-flag" />
                        <p>USD,NYSE</p>
                    </div>
                </div>
            </div>

            <div className="stock-detail grid grid-cols-2 gap-8 mt-5 text-brown-sugar">
                <div className="stock-card-detail p-5 bg-white border border-solid border-1 border-gray-500 rounded-lg">
                    <div className="grid grid-cols-2">
                        <div className="f-1 me-10">
                            <div className="t-box">
                                <h2 className="font-bold mb-2">รายละเอียดบริษัท</h2>
                                <hr className="h-line" />

                                <div className="t-box-detail mt-3">
                                    <p>
                                    {showMore
                                        ? `International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.`
                                        : `International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York...`}
                                    </p>
                                    <button
                                        className="text-blue-500 mt-2"
                                        onClick={toggleShowMore}
                                    >
                                    {showMore ? "แสดงน้อยลง" : "อ่านเพิ่มเติม"}
                                    </button>
                                </div>
                            </div>

                            <div className="t-box mt-5">
                                <h2 className="font-bold mb-2">เว็บไซต์</h2>
                                <hr className="h-line" />

                                <div className="t-box-detail mt-3">
                                    <p>ibm.com</p>
                                </div>
                            </div>

                            <div className="t-box mt-5">
                                <h2 className="font-bold mb-2">ที่อยู่</h2>
                                <hr className="h-line" />

                                <div className="t-box-detail mt-3">
                                    <p>1 NEW ORCHARD ROAD, ARMONK, NY, US</p>
                                </div>
                            </div>

                            <div className="t-box mt-5">
                                <h2 className="font-bold mb-2">มูลค่าตามราคาตลาด (Marketcap)</h2>
                                <hr className="h-line" />

                                <div className="t-box-detail mt-3">
                                    <p>$186,191,659,000</p>
                                </div>
                            </div>
                        </div>

                        <div className="f-2">
                            <div className="t-box mb-5">
                                <h2 className="font-bold mb-2">Sector</h2>
                                <hr className="h-line" />

                                <div className="t-box-detail mt-3">
                                    <p>TECHNOLOGY</p>
                                </div>
                            </div>

                            <div className="t-box mb-5">
                                <h2 className="font-bold mb-2">Industry</h2>
                                <hr className="h-line" />

                                <div className="t-box-detail mt-3">
                                    <p>COMPUTER & OFFICE EQUIPMENT</p>
                                </div>
                            </div>

                            <div className="t-box mb-5">
                                <h2 className="font-bold mb-2">ประเภทหลักทรัพย์</h2>
                                <hr className="h-line" />

                                <div className="t-box-detail mt-3">
                                    <p>Common Stock</p>
                                </div>
                            </div>

                            <div className="t-box mb-5">
                                <h2 className="font-bold mb-2">เงินปันผล</h2>
                                <hr className="h-line" />

                                <div className="t-box-detail mt-3">
                                    <p>$6.65, 0.033%</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="stock-card-detail p-2 pt-10 bg-white border border-solid border-1 border-gray-500 rounded-lg">
                    <LineChart width={500} height={200} data={chartData}>
                        <CartesianGrid strokeDasharray="3 3" />
                        <XAxis dataKey="date" />
                        <YAxis />
                        <Tooltip />
                        <Legend />
                        <Line type="monotone" dataKey="price" stroke="#70E2B8" />
                    </LineChart>
                </div>
            </div>

            <div className="financial-statements">
                                 
            </div>
        </>
    );
};

export default AmaricaStocks;